name: Build and Deploy Spot Shorter Development Environment

on:
  push: 
    branches: 
      - develop
  workflow_dispatch:

env:
  PROJECT_ID: spot_app_development
  DEPLOY_DIR: /home/ccjd.0706/spot-app-development
  ANALIZER_DIR: /home/ccjd.0706/spot-app-development/analizer

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Copy Source Code"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          source: './'
          target: ${{ env.DEPLOY_DIR }}
          strip_components: 1

      - name: "Build And Deploy to server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            EOF
            cd ${{ env.ANALIZER_DIR }}
            cat << EOF > ./.env
            ${{ secrets.ANALIZER_DEV_ENV_FILE }}
            EOF
            cd ${{ env.DEPLOY_DIR }}
            cat << EOF > ./.env
            ${{ secrets.DEV_ENV_FILE }}
            docker compose -f docker-compose-development.yml down
            docker compose -f docker-compose-development.yml up --build -d
            docker exec spot_app_dev sh -c  'chmod 777 -R ./storage/'
            docker exec spot_app_dev sh -c  'npm run build'
            docker image prune -a --force --filter "until=168h"

 