name: Build and Deploy Spot Shorter Production Environment

on:
  push: 
    branches: 
      - master
  workflow_dispatch:

env:
  PROJECT_ID: spot_app_production
  DEPLOY_DIR: /home/ccjd.0706/spot-app-production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Copy Source Code"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          source: './'
          target: ${{ env.DEPLOY_DIR }}
          strip_components: 1

      - name: "Build And Deploy to server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            cd ${{ env.DEPLOY_DIR }}
            cat << EOF > ./.env
            ${{ secrets.PROD_ENV_FILE }}
            EOF
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml up --build -d
            docker exec spot_app sh -c  'chmod 777 -R ./storage/'
            docker exec spot_app sh -c  'npm run build'
            docker image prune -a --force --filter "until=168h"

 